{% set name = "JTango" %}
{% set version = "9.6.8" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://gitlab.com/tango-controls/JTango/-/archive/{{ version }}/JTango-{{ version }}.tar.gz
  sha256: 64928e1dd38ea80a2b873737599b400dba7469c581bfb07e017a21c8bafe5ab7

build:
  number: 0
  noarch: generic

requirements:
  build:
    - openjdk 8
    - maven
  run:
    - openjdk >=8

test:
  commands:
    - test -f ${PREFIX}/share/java/JTango.jar
    - test -f ${PREFIX}/share/java/JTango-${PKG_VERSION}.jar

about:
  home: https://www.tango-controls.org
  license: LGPL-3.0-or-later
  license_file:
    - LICENSE
    - aggregate-third-party-report.html

  summary: 'TANGO kernel Java implementation.'
  description: |
    TANGO kernel Java implementation. Compatible with Java 8 and onwards.
    Tango-Controls is a software toolkit for building control systems.
  doc_url: https://jtango.readthedocs.io/
  dev_url: https://gitlab.com/tango-controls/JTango

extra:
  recipe-maintainers:
    - beenje
